/**
 * Shared prompt builders for text generation providers.
 *
 * Extracts the prompt construction logic that is identical across
 * Codex, Claude, and any future CLI-based text generation backends.
 *
 * @module textGenerationPrompts
 */
import { Schema } from "effect";
import type { ChatAttachment } from "@t3tools/contracts";
import { CONVENTIONAL_BRANCH_TYPES } from "@t3tools/shared/git";

import { limitSection } from "./Utils.ts";

const CONVENTIONAL_BRANCH_TYPES_JOINED = CONVENTIONAL_BRANCH_TYPES.join(", ");
const ConventionalBranchTypeSchema = Schema.Literals(CONVENTIONAL_BRANCH_TYPES);

// ---------------------------------------------------------------------------
// Commit message
// ---------------------------------------------------------------------------

export interface CommitMessagePromptInput {
  branch: string | null;
  stagedSummary: string;
  stagedPatch: string;
  includeBranch: boolean;
}

export function buildCommitMessagePrompt(input: CommitMessagePromptInput) {
  const wantsBranch = input.includeBranch;

  const prompt = [
    "You write concise git commit messages.",
    wantsBranch
      ? "Return a JSON object with keys: subject, body, branchType, branchName."
      : "Return a JSON object with keys: subject, body.",
    "Rules:",
    "- subject must be imperative, <= 72 chars, and no trailing period",
    "- body can be empty string or short bullet points",
    "- capture the primary user-visible or developer-visible change",
    "- do NOT include attribution, trailers, sign-offs, or any 'Generated by' / 'Co-authored-by' footers",
    ...(wantsBranch
      ? [
          `- branchType MUST be one of: ${CONVENTIONAL_BRANCH_TYPES_JOINED}`,
          "- pick the branchType that best matches the primary intent of the change",
          "- branchName describes the change in 2-6 plain lowercase words (hyphens or slashes only); no issue prefixes, no branchType prefix",
        ]
      : []),
    "",
    `Branch: ${input.branch ?? "(detached)"}`,
    "",
    "Staged files:",
    limitSection(input.stagedSummary, 6_000),
    "",
    "Staged patch:",
    limitSection(input.stagedPatch, 40_000),
  ].join("\n");

  if (wantsBranch) {
    return {
      prompt,
      outputSchema: Schema.Struct({
        subject: Schema.String,
        body: Schema.String,
        branchType: ConventionalBranchTypeSchema,
        branchName: Schema.String,
      }),
    };
  }

  return {
    prompt,
    outputSchema: Schema.Struct({
      subject: Schema.String,
      body: Schema.String,
    }),
  };
}

// ---------------------------------------------------------------------------
// PR content
// ---------------------------------------------------------------------------

export interface PrContentPromptInput {
  baseBranch: string;
  headBranch: string;
  commitSummary: string;
  diffSummary: string;
  diffPatch: string;
}

export function buildPrContentPrompt(input: PrContentPromptInput) {
  const prompt = [
    "You write GitHub pull request content that documents the thought process, not just the diff.",
    "Return a JSON object with keys: title, body.",
    "",
    "Title rules:",
    "- concise, specific, imperative mood, <= 72 chars, no trailing period",
    "- no issue prefixes or emoji",
    "",
    "Body template (markdown):",
    "",
    "  ## Why",
    "  1-3 sentences on the problem being solved or the motivation for the change.",
    "  This is the reason the change exists, not a restatement of the diff.",
    "",
    "  ## What changed",
    "  3-6 short bullets describing user- or developer-visible deltas.",
    "  Reference files, modules, or components only when it clarifies scope.",
    "",
    "  ## Notable decisions",
    "  Only when real trade-offs exist: why X over Y, what was considered and rejected,",
    "  known limitations, follow-ups. Omit this section entirely when not applicable.",
    "",
    "  ## Testing",
    "  Concrete checks run, or 'Not run' where appropriate.",
    "",
    "Body rules:",
    "- omit any section that would contain only filler — do not pad",
    "- prefer <= ~200 words total unless the change genuinely warrants more",
    "- write in first-principles, direct prose; no marketing tone, no hedging",
    "- do NOT include attribution, sign-offs, or 'Generated by' / 'Co-authored-by' footers",
    "",
    `Base branch: ${input.baseBranch}`,
    `Head branch: ${input.headBranch}`,
    "",
    "Commits:",
    limitSection(input.commitSummary, 12_000),
    "",
    "Diff stat:",
    limitSection(input.diffSummary, 12_000),
    "",
    "Diff patch:",
    limitSection(input.diffPatch, 40_000),
  ].join("\n");

  const outputSchema = Schema.Struct({
    title: Schema.String,
    body: Schema.String,
  });

  return { prompt, outputSchema };
}

// ---------------------------------------------------------------------------
// Branch name
// ---------------------------------------------------------------------------

export interface BranchNamePromptInput {
  message: string;
  attachments?: ReadonlyArray<ChatAttachment> | undefined;
}

interface PromptFromMessageInput {
  instruction: string;
  responseShape: string;
  rules: ReadonlyArray<string>;
  message: string;
  attachments?: ReadonlyArray<ChatAttachment> | undefined;
}

function buildPromptFromMessage(input: PromptFromMessageInput): string {
  const attachmentLines = (input.attachments ?? []).map(
    (attachment) => `- ${attachment.name} (${attachment.mimeType}, ${attachment.sizeBytes} bytes)`,
  );

  const promptSections = [
    input.instruction,
    input.responseShape,
    "Rules:",
    ...input.rules.map((rule) => `- ${rule}`),
    "",
    "User message:",
    limitSection(input.message, 8_000),
  ];
  if (attachmentLines.length > 0) {
    promptSections.push(
      "",
      "Attachment metadata:",
      limitSection(attachmentLines.join("\n"), 4_000),
    );
  }

  return promptSections.join("\n");
}

export function buildBranchNamePrompt(input: BranchNamePromptInput) {
  const prompt = buildPromptFromMessage({
    instruction:
      "You generate concise git branch names in conventional-commits style (<type>/<name>).",
    responseShape: "Return a JSON object with keys: type, name.",
    rules: [
      `type MUST be one of: ${CONVENTIONAL_BRANCH_TYPES_JOINED}`,
      "Pick the type that best matches the primary intent of the requested work.",
      "name describes the work in 2-6 plain lowercase words. Use hyphens to separate words.",
      "No issue prefixes, no punctuation-heavy text, and do not repeat the type in the name.",
      "If images are attached, use them as primary context for visual/UI issues.",
    ],
    message: input.message,
    attachments: input.attachments,
  });
  const outputSchema = Schema.Struct({
    type: ConventionalBranchTypeSchema,
    name: Schema.String,
  });

  return { prompt, outputSchema };
}

// ---------------------------------------------------------------------------
// Thread title
// ---------------------------------------------------------------------------

export interface ThreadTitlePromptInput {
  message: string;
  attachments?: ReadonlyArray<ChatAttachment> | undefined;
}

export function buildThreadTitlePrompt(input: ThreadTitlePromptInput) {
  const prompt = buildPromptFromMessage({
    instruction: "You write concise thread titles for coding conversations.",
    responseShape: "Return a JSON object with key: title.",
    rules: [
      "Title should summarize the user's request, not restate it verbatim.",
      "Keep it short and specific (3-8 words).",
      "Avoid quotes, filler, prefixes, and trailing punctuation.",
      "If images are attached, use them as primary context for visual/UI issues.",
    ],
    message: input.message,
    attachments: input.attachments,
  });
  const outputSchema = Schema.Struct({
    title: Schema.String,
  });

  return { prompt, outputSchema };
}
